
#define ADMUX ACCES_REGISTER_ADDRESS(0x07)
enum{MUX0, MUX1, MUX2, MUX3, MUX4, ADLAR, REFS0, REFS1};

#define ADCSRA ACCES_REGISTER_ADDRESS(0x06)
enum{ADPS0, ADPS1, ADPS2, ADIE, ADIF, ADATE, ADSC, ADEN};

#define ADCH ACCES_REGISTER_ADDRESS(0x05)
#define ADCL ACCES_REGISTER_ADDRESS(0x04)


